version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "integration"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "cicd"
      - "automation"
    open-pull-requests-limit: 5
    groups:
      # Group all github-actions updates into a single PR
      github-actions:
        patterns:
          - "*"
