apiVersion: v2
name: holmes
description: A Helm chart to deploy OLM (Operator Lifecycle Manager) in Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
icon: https://avatars.githubusercontent.com/u/38202270?s=280&v=4
keywords:
  - olm
  - operator
  - operator-lifecycle-manager
  - operators
  - kubernetes
home: https://github.com/aRustyDev/helm-charts
sources:
  - https://github.com/aRustyDev/helm-charts
  - https://github.com/operator-framework/operator-lifecycle-manager
maintainers:
  - name: aRustyDev
    email: arustydev@proton.me
    url: https://github.com/aRustyDev
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: integration-delivery
  artifacthub.io/links: |
    - name: OLM Documentation
      url: https://olm.operatorframework.io/
    - name: OperatorHub
      url: https://operatorhub.io/
  artifacthub.io/operator: "true"
  artifacthub.io/crds: |
    - kind: CatalogSource
      version: v1alpha1
      name: catalogsources.operators.coreos.com
    - kind: ClusterServiceVersion
      version: v1alpha1
      name: clusterserviceversions.operators.coreos.com
    - kind: Subscription
      version: v1alpha1
      name: subscriptions.operators.coreos.com
