apiVersion: v2
name: test-workflow
description: Test chart for E2E workflow validation
type: application
version: 0.1.3
appVersion: "1.0.0"
maintainers:
  - name: aRustyDev
    url: https://github.com/aRustyDev
keywords:
  - test
  - e2e
  - workflow
home: https://github.com/aRustyDev/helm-charts
sources:
  - https://github.com/aRustyDev/helm-charts
