{{- if .Values.e2eTest.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-workflow.fullname" . }}-e2e
  labels:
    {{- include "test-workflow.labels" . | nindent 4 }}
data:
  replicas: "{{ .Values.e2eTest.replicas }}"
  message: {{ .Values.e2eTest.message | quote }}
{{- end }}
